Create DiagrammeDéploiement.puml
INDEN-Intelligo/Design pull request #16
Opened 2023-01-12 08:01 UTC by Payll

2023-01-15 12:48 UTC, Slonev0 requested changes
Need to translate "Collecteurs" to Collector ?

2023-01-15 15:02 UTC, Payll commented
Need to wait before merge

2023-02-09 08:32 UTC, Slonev0 approved these changes

2023-03-09 09:34 UTC, ghost-hikaru approved these changes
Best diagram in the world I never see a diagram like this

2023-03-09 09:34 UTC, merged