add new tech to the wiki
INDEN-Intelligo/Design pull request #18
Opened 2023-01-14 13:07 UTC by ghost-hikaru

2023-01-14 17:26 UTC, Slonev0 requested changes
just need to correct a spelling mistake after

2023-01-14 17:26 UTC, Slonev0 commented on temp/wiki.md
> +- Unité central de controle et de stockage
Centrale* et contrôle*

2023-02-09 08:19 UTC, Payll approved these changes
Remove .DS_Store after

2023-02-09 08:20 UTC, Slonev0 approved these changes
thx :)

2023-02-09 08:20 UTC, merged